from google.cloud import translate
from google.oauth2 import service_account


def key_to_value(choice):
    return languages[choice.lower()]


def translate_text(text):
    file = open("Settings.txt", "r")
    language_of_choice = file.read()

    translation = translate_client.translate(
        text,
        target_language=key_to_value(language_of_choice))

    output = translation['translatedText']
    return output


languages = {'afrikaans': "af",
             'albanian': "sq",
             'amharic': "am",
             'arabic': "ar",
             'armenian': "hy",
             'azerbaijani': "az",
             'basque': "eu",
             'belarusian': "be",
             'bengali': "bn",
             'bosnian': "bs",
             'bulgarian': "bg",
             'catalan': "ca",
             'corsican': "co",
             'croatian': "hr",
             'czech': "cs",
             'danish': "da",
             'dutch': "nl",
             'english': "en",
             'esperanto': "eo",
             'estonian': "et",
             'finnish': "fi",
             'french': "fr",
             'frisian': "fy",
             'galician': "gl",
             'georgian': "ka",
             'german': "de",
             'greek': "el",
             'gujarati': "gu",
             'haitian': "ht",
             'crole': "ht",
             'hausa': "ha",
             'hawaiian': "ha",
             'hebrew': "he**",
             'hindi': "hi",
             'hmong': "hm",
             'hungarian': "hu",
             'icelandic': "is",
             'tgbo': "ig",
             'indonesian': "id",
             'irish': "ga",
             'italian': "it",
             'japanese': "ja",
             'javanese': "jw",
             'kannada': "kn",
             'kazakh': "kk",
             'khmer': "km",
             'korean': "ko",
             'kurdish': "ku",
             'kyrgyz': "ky",
             'Lao': "lo",
             'latin': "la",
             'latvian': "lv",
             'lithuanian': "lt",
             'luxembourgish': "lb",
             'macedonian': "mk",
             'malagasy': "mg",
             'malay': "ms",
             'Malayalam': "ml",
             'maltese': "mt",
             'maori': "mi",
             'marathi': "mr",
             'mongolian': "mn",
             'myanmar': "my",
             'burmese': "my",
             'nepali': "ne",
             'norwegian': "no",
             'nyanja': "ny",
             'chichewa': "ny",
             'pashto': "ps",
             'persian': "fa",
             'polish': "pl",
             'portuguese': "pt",
             'punjabi': "pa",
             'romanian': "ro",
             'russian': "ru",
             'samoan': "sm",
             'scots': "gd",
             'gaelic': "gd",
             'serbian': "sr",
             'sesotho': "st",
             'shona': "sn",
             'sindhi': "sd",
             'sinhala': "si",
             'sinhalese': "si",
             'slovak': "sk",
             'slovenian': "sl",
             'somali': "so",
             'spanish': "es",
             'sundanese': "su",
             'swahili': "sw",
             'swedish': "sv",
             'sagalog': "tl",
             'filipino': "tl",
             'tajik': "tg",
             'tamil': "ta",
             'telugu': "te",
             'thai': "th",
             'turkish': "tr",
             'ukrainian': "uk",
             'urdu': "ur",
             'uzbek': "uz",
             'vietnamese': "vi",
             'welsh': "cy",
             'xhosa': "xh",
             'yiddish': "yi",
             'yoruba': "yo",
             'zulu': "zu", }

credentials = service_account.Credentials.from_service_account_file('HackFree2019.json')
translate_client = translate.Client(credentials=credentials)  # Instantiates client
